version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - "server"

  server:
    build: ./server
    volumes:
      - ./server/:/go/src/github.com/alitaso345/synchronicity2/server
    ports:
      - "9090:9090"
    container_name: "server"
    environment:
      TWITCH_PASSWORD: "${TWITCH_PASSWORD}"
      TWITCH_NICK: "${TWITCH_NICK}"
      TWITTER_CONSUMER_KEY: "${TWITTER_CONSUMER_KEY}"
      TWITTER_CONSUMER_SECRET: "${TWITTER_CONSUMER_SECRET}"
      TWITTER_ACCESS_TOKEN: "${TWITTER_ACCESS_TOKEN}"
      TWITTER_ACCESS_TOKEN_SECRET: "${TWITTER_ACCESS_TOKEN_SECRET}"

  client:
    build: ./client
    command: "yarn dev"
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
