version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy.Dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - server
    container_name: synchronicity2-proxy

  server:
    build:
      context: .
      dockerfile: ./docker/server.development.Dockerfile
    #      dockerfile: ./docker/server.Dockerfile
    volumes:
      - ./:/app/
    ports:
      - "9000:9000"
    container_name: synchronicity2-server
    environment:
      TWITCH_PASSWORD: "${TWITCH_PASSWORD}"
      TWITCH_NICK: "${TWITCH_NICK}"
      TWITTER_CONSUMER_KEY: "${TWITTER_CONSUMER_KEY}"
      TWITTER_CONSUMER_SECRET: "${TWITTER_CONSUMER_SECRET}"
      TWITTER_ACCESS_TOKEN: "${TWITTER_ACCESS_TOKEN}"
      TWITTER_ACCESS_TOKEN_SECRET: "${TWITTER_ACCESS_TOKEN_SECRET}"

  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    volumes:
      - ./client:/client/
    ports:
      - "3000:3000"
    container_name: synchronicity2-client