apiVersion: apps/v1
kind: Deployment
metadata:
  name: synchronicity2-server
spec:
  selector:
    matchLabels:
      app: synchronicity2-server
  template:
    metadata:
      labels:
        app: synchronicity2-server
    spec:
      containers:
        - name: server
          image: gcr.io/synchronicity2/synchronicity2-server
          ports:
            - containerPort: 9000